---
name: Build

on:
  push:

env:
  IN_CI: '1'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - uses: actions/checkout@v2

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - run: pipenv sync --system --dev
      - run: python3 -m pip install --quiet --user -e .
      - run: prospector .
      - run: >
            coverage run --source=deskew --module pytest --durations=0 --verbose --color=yes
            --profile --profile-svg --junitxml=results/test-reports/junit.xml tests &&
            coverage report &&
            coverage html --directory=results/coverage

      - uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: results/test-reports

      - name: Init Git
        run: |
          git config credential.helper 'cache --timeout=120'
          git config user.email "<ci@ci.com>"
          git config user.name "CI"
      - name: Init pypi
        run: |
            echo "[pypi]" > ~/.pypirc
            echo "username = ${{ secrets.PYPI_USERNAME }}" >> ~/.pypirc
            echo "password = ${{ secrets.PYPI_PASSWORD }}" >> ~/.pypirc
            python3 -m pip install --user wheel twine
      - name: Bump version
        run: |
          python3 -m pip install --user bump-anything
          bump patch
          git add setup.py
          git commit --allow-empty -m "[skip ci] Bump Version"
          git push
        if: github.ref == 'refs/heads/master'
      - name: deploy
        run: |
          python3 setup.py egg_info --no-date sdist bdist_wheel
          python3 -m twine upload dist/*
        if: github.ref == 'refs/heads/master'
